# **Data Preprocessing Tools**
## Machine Learning

<img src="https://upload.wikimedia.org/wikipedia/commons/6/68/LOGO_UEU_BY_ASU-06.png" width=50% height=50%>

<table style="width:75%">
  <tr>
    <td><b>Dosen Pengampu</b></td>
    <td>Jefry Sunupurwa Asri , S.Kom., M.Kom.</td>
   </tr>
  <tr>
    <td><b>Mahasiswa</b></td>
    <td>Andika Noor Ismawan</td>
  </tr>
  <tr>
    <td><b>NIM</b></td>
    <td>20210801465</td>
  </tr>
</table>

<hr>

### Importing Libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

<hr>

### Importing the dataset

In [4]:
dataset = pd.read_csv('../Pertemuan3/Dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
z = dataset.iloc[[2]].values

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [6]:
dataset.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [7]:
dataset.isnull().sum().sum()

2

In [8]:
print(z)

[['Germany' 30.0 54000.0 'No']]


In [9]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [10]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


<hr>

### Taking care of missing data

In [12]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [ ]:
print(X)

[[101 'John' 'Doe' 'johndoe@example.com' 'HR' 'HR Manager' 60000.0
  '2020-03-15']
 [102 'Jane' 'Smith' 'janesmith@example.com' 'Finance' 'Accountant'
  50000.0 '2019-07-20']
 [103 'Michael' 'Johnson' 'michaeljohnson@example.com' 'IT'
  'Software Engineer' 55375.0 '2021-01-10']
 [104 'Emily' 'Williams' 'emilywilliams@example.com' 'Marketing'
  'Marketing Manager' 65000.0 '2018-11-05']
 [105 'David' 'Brown' 'davidbrown@example.com' 'Sales'
  'Sales Representative' 55000.0 '2020-09-30']
 [106 'Lisa' 'Miller' 'lisamiller@example.com' 'HR' 'HR Specialist'
  55375.0 '2019-02-12']
 [107 'Robert' 'Anderson' 'robertanderson@example.com' 'Finance'
  'Financial Analyst' 55000.0 '2020-06-25']
 [108 'Susan' 'Clark' 'susanclark@example.com' 'IT'
  'Database Administrator' 68000.0 '2019-04-08']
 [109 'Matthew' 'White' 'matthewwhite@example.com' 'Marketing'
  'Marketing Coordinator' 48000.0 '2021-03-20']
 [110 'Laura' 'Taylor' 'laurataylor@example.com' 'Sales' 'Sales Manager'
  75000.0 '2018-08-14']


# Encoding Categorical Data

<hr>

## Encoding the Independent Variable

In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [14]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


## Encoding the Independent Variable

In [16]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [17]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [19]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [20]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [21]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [22]:
print(y_test)

[0 1]


## Feature Scaling

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [25]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [26]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
