# **Tugas Pertemuan 2**
## Machine Learning

<img src="https://upload.wikimedia.org/wikipedia/commons/6/68/LOGO_UEU_BY_ASU-06.png" width=50% height=50%>

<table style="width:75%">
  <tr>
    <td><b>Dosen Pengampu</b></td>
    <td>Jefry Sunupurwa Asri , S.Kom., M.Kom.</td>
   </tr>
  <tr>
    <td><b>Mahasiswa</b></td>
    <td>Andika Noor Ismawan</td>
  </tr>
  <tr>
    <td><b>NIM</b></td>
    <td>20210801465</td>
  </tr>
</table>

<hr>

**1. Buatlah identitas diri menggunakan pemograman python sederhana**

In [10]:
nama_mahasiswa = "Andika Noor Ismawan"
nim_mahasiswa = "20210801465"
mata_kuliah = "Machine Learning - CIE407"

output = f"{'Nama Mahasiswa:':<15} {nama_mahasiswa}\n" \
         f"{'NIM Mahasiswa:':<15} {nim_mahasiswa}\n" \
         f"{'Mata Kuliah:':<15} {mata_kuliah}"

print("Informasi Mahasiswa:")
print(output)

Informasi Mahasiswa:
Nama Mahasiswa: Andika Noor Ismawan
NIM Mahasiswa:  20210801465
Mata Kuliah:    Machine Learning - CIE407


**2. Buatlah matriks C dengan orde 2x3, dan nilai yang diberikan pada matriks C adalah sebagai berikut:**
<ul>
  <li>Baris 1 Kolom 1, nilai = 1</li>
  <li>Baris 1 Kolom 2, nilai = 2</li>
  <li>Baris 1 Kolom 3, nilai = 3</li>
  <li>Baris 2 Kolom 1, nilai = 4</li>
  <li>Baris 2 Kolom 2, nilai = 5</li>
  <li>Baris 2 Kolom 3, nilai = 6</li>
</ul>

In [20]:
matriksC = [ [1, 2, 3], [4, 5, 6]]

print("Matriks C Ordo 2x3:")
print(matriksC)

Matriks C Ordo 2x3:
[[1, 2, 3], [4, 5, 6]]


**3. Buatlah matriks dengan orde 3x2, dengan nilai adalah:**
<ul>
  <li>Baris 1 Kolom 1, nilai = 2</li>
  <li>Baris 1 Kolom 2, nilai = 2</li>
  <li>Baris 2 Kolom 1, nilai = 2</li>
  <li>Baris 2 Kolom 2, nilai = 2</li>
  <li>Baris 3 Kolom 1, nilai = 2</li>
  <li>Baris 3 Kolom 2, nilai = 2</li>
</ul>

In [21]:
matriks = [[2, 2], [2, 2], [2, 2]]

print("Matriks dengan ordo 3x2:")
print(matriks)

Matriks dengan ordo 3x2:
[[2, 2], [2, 2], [2, 2]]


**4. Importlah library Numpy**

In [ ]:
import numpy as np

/*
NumPy (Numerical Python) adalah library Python yang fokus pada scientific computing.

Numpy menyediakan fungsi yang siap pakai untuk memudahkan melakukan perhitungan saintifik seperti matriks, aljabar, statistik, dan sebagainya.
*/

**5. Dengan memanfaatkan library numpy Buatlah matriks dengan menggunakan Library Numpy dengan panjang elemen adalah 32 dan matriks memiliki orde 4x8**

In [4]:
import numpy as np

m = 4 #baris
n = 8 #kolom

matriks = np.arange(m*n).reshape(m, n)

print(matriks)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


**6. Buatlah matriks dengan menggunakan Library Numpy dengan orde 3x30, dan nilai elemen dimulai dari indeks 1 sampai dengan 5 secara random.**

In [9]:
import numpy as np

m = 3  # baris
n = 30  # kolom

matriks_acak = np.random.randint(1, 5, size=(m, n))

print(matriks_acak)

[[2 3 3 3 3 2 1 4 2 1 1 4 2 3 2 3 4 3 2 3 3 4 1 2 4 1 2 2 1 2]
 [1 1 2 2 4 4 1 3 4 2 3 3 3 1 3 4 1 3 1 3 3 4 1 2 4 4 1 3 3 2]
 [3 2 3 1 2 4 2 1 2 3 3 4 3 3 2 1 2 2 3 2 3 1 3 2 1 4 4 2 2 3]]
